In [1]:
import torch
import torch.nn as nn
from abc import ABC, abstractmethod

# Q1

In [2]:
class Softmax(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        exp_x = torch.exp(x)
        return exp_x/torch.sum(exp_x)

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        max_x = torch.max(x)
        exp_x = torch.exp(x-max_x)
        return exp_x/torch.sum(exp_x)

data = torch.Tensor([1, 2, 3])
softmax = Softmax()
output = softmax(data)
print(output)

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
print(output)

tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])


# Q2

In [3]:
class Person(ABC):
    def __init__(self, name: str, yob: int):
        self.name = name
        self.yob = yob

    def get_yob(self):
        return self.yob

    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: str):
        super().__init__(name, yob)
        self.grade = grade
    def describe(self):
        print(f'Student - Name: {self.name} - YoB: {self.yob} - Grade: {self.grade}')

class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str):
        super().__init__(name, yob)
        self.subject = subject
    def describe(self):
        print(f'Teacher - Name: {self.name} - YoB: {self.yob} - Subject: {self.subject}')

class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: str):
        super().__init__(name, yob)
        self.specialist = specialist
    def describe(self):
        print(f'Doctor - Name: {self.name} - YoB: {self.yob} - specialist: {self.specialist}')

class Ward:
    def __init__(self, name: str):
        self.name = name
        self.peoplelist = list()

    def add_person(self, person: Person):
        self.peoplelist.append(person)

    def describe(self):
        print(f'Ward Name: {self.name}')
        for i in self.peoplelist:
            i.describe()

    def count_doctor(self):
        count = 0
        for i in self.peoplelist:
            if isinstance(i, Doctor):
                count += 1
        return count

    def sort_age(self):
        self.peoplelist.sort(key=lambda i: i.get_yob(), reverse=True)

    def compute_average(self):
        teachers = []
        for i in self.peoplelist:
            if isinstance(i, Teacher):
                teachers.append(i.get_yob())
        if len(teachers) == 0:
            return 0
        return sum(teachers)/len(teachers)

Test case

In [4]:
#2a
print('2a:')
student1 = Student(name='studentA', yob=2010, grade='7')
student1.describe()
teacher1 = Teacher(name='teacherA', yob=1969, subject='Math')
teacher1.describe()
doctor1 = Doctor(name='doctorA', yob=1945, specialist='Endocrinologists')
doctor1.describe()

#2b
print('\n2b:')
teacher2 = Teacher(name='teacherB', yob=1995, subject='History')
doctor2 = Doctor(name='doctorB', yob=1975, specialist='Cardiologists')
ward1 = Ward(name ='Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.describe()

#2c
print('\n2c:')
print(f'Number of doctors: {ward1.count_doctor()}')

#2d
print('\n2d:')
print('After sorting Age of Ward1 people:')
ward1.sort_age()
ward1.describe()

#2e
print('\n2e:')
print(f'Average year of birth (teachers): {ward1.compute_average()}')

2a:
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - specialist: Endocrinologists

2b:
Ward Name: Ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorA - YoB: 1945 - specialist: Endocrinologists
Doctor - Name: doctorB - YoB: 1975 - specialist: Cardiologists

2c:
Number of doctors: 2

2d:
After sorting Age of Ward1 people:
Ward Name: Ward1
Student - Name: studentA - YoB: 2010 - Grade: 7
Teacher - Name: teacherB - YoB: 1995 - Subject: History
Doctor - Name: doctorB - YoB: 1975 - specialist: Cardiologists
Teacher - Name: teacherA - YoB: 1969 - Subject: Math
Doctor - Name: doctorA - YoB: 1945 - specialist: Endocrinologists

2e:
Average year of birth (teachers): 1982.0


# Q3

In [5]:
class Stack:
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.stack = []
    
    def is_empty(self):
        return len(self.stack) == 0
    
    def is_full(self):
        return len(self.stack) == self.capacity
    
    def pop(self):
        if self.is_empty():
            return 'Stack is empty'
        pop_val = self.top()
        self.stack.pop()
        return pop_val

    def push(self, value):
        if self.is_full():
            return 'Stack is full'
        self.stack.append(value)

    def top(self):
        if self.is_empty():
            return 'Stack is empty'
        else:
            return self.stack[-1]

Test case

In [6]:
stack1 = Stack(capacity=5)

stack1.push(1)
stack1.push(2)

print(stack1.is_full())
print(stack1.top())
print(stack1.pop())
print(stack1.top())
print(stack1.pop())
print(stack1.is_empty())

False
2
2
1
1
True


# Q4

In [7]:
class Queue:
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.queue = []

    def is_empty(self):
        return len(self.queue) == 0
    
    def is_full(self):
        return len(self.queue) == self.capacity
    
    def dequeue(self):
        if self.is_empty():
            return 'Queue is empty'
        dequeue_val = self.front()
        self.queue.pop(0)
        return dequeue_val
    
    def enqueue(self, value):
        if self.is_full():
            return 'Queue is full'
        self.queue.append(value)

    def front(self):
        if self.is_empty():
            return 'Queue is empty'
        return self.queue[0]

Test case

In [8]:
queue1 = Queue(capacity=5)

queue1.enqueue(1)
queue1.enqueue(2)

print(queue1.is_full())
print(queue1.front())
print(queue1.dequeue())
print(queue1.front())
print(queue1.dequeue())
print(queue1.is_empty())

False
1
1
2
2
True


# Multiple choice

Q1

In [9]:
data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

Q2

In [10]:
data = torch.Tensor([5, 2, 4])
my_softmax = Softmax()
output = my_softmax(data)
assert round(output[-1].item(), 2) == 0.26
print(output)

tensor([0.7054, 0.0351, 0.2595])


Q3

In [11]:
data = torch.Tensor([1, 2, 300000000])
my_softmax = Softmax()
output = my_softmax(data)
assert round(output[0].item(), 2) == 0.0
print(output)

tensor([0., 0., nan])


Q4

In [12]:
data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[-1].item(), 2) == 0.67
print(output)

tensor([0.0900, 0.2447, 0.6652])


Q5

In [13]:
student1 = Student(name ='studentZ2023', yob =2011, grade ='6')
assert student1.yob == 2011
student1.describe ()

Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


Q6

In [14]:
teacher1 = Teacher(name='teacherZ2023', yob=1991, subject='History')
assert teacher1.yob == 1991
teacher1.describe()

Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History


Q7

In [15]:
doctor1 = Doctor(name='doctorZ2023', yob=1981, specialist='Endocrinologists')
assert doctor1.yob == 1981
doctor1.describe()

Doctor - Name: doctorZ2023 - YoB: 1981 - specialist: Endocrinologists


Q8

In [16]:
student1 = Student(name='studentA', yob=2010, grade='7')
teacher1 = Teacher(name='teacherA', yob=1969, subject='Math')
teacher2 = Teacher(name='teacherB', yob=1995, subject='History')
doctor1 = Doctor(name='doctorA', yob=1945, specialist='Endocrinologists')
doctor2 = Doctor(name='doctorB', yob=1975, specialist='Cardiologists')
ward1 = Ward(name='Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
assert ward1.count_doctor() == 1
ward1.add_person(doctor2)
ward1.count_doctor()

2

Q9

In [17]:
stack1 = Stack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.is_full())

False


Q10

In [18]:
stack1 = Stack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.top())

2


Q11

In [19]:
queue1 = Queue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full())

False


Q12

In [20]:
queue1 = Queue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.front())

1
