In [44]:
import numpy as np

Q1

In [45]:
def df_w(W):
    dw1 = 0.2 * W[0]
    dw2 = 4 * W[1]
    dW = np.array([dw1, dw2])
    return dW

def sgd(W, dW, lr):
    W = W - lr * dW
    return W

def train_p1(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype=np.float32)
    results = [W]
    for epoch in range(epochs):
        dW = df_w(W)
        W = optimizer(W, dW, lr)
        results.append(W)
    return results

train_p1(sgd, lr=0.4, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.6,  1.2]),
 array([-4.232, -0.72 ]),
 array([-3.89344,  0.432  ]),
 array([-3.5819648, -0.2592   ]),
 array([-3.29540762,  0.15552   ]),
 array([-3.03177501, -0.093312  ]),
 array([-2.78923301,  0.0559872 ]),
 array([-2.56609437, -0.03359232]),
 array([-2.36080682,  0.02015539]),
 array([-2.17194227, -0.01209324]),
 array([-1.99818689,  0.00725594]),
 array([-1.83833194, -0.00435356]),
 array([-1.69126538,  0.00261214]),
 array([-1.55596415, -0.00156728]),
 array([-1.43148702e+00,  9.40369969e-04]),
 array([-1.31696806e+00, -5.64221981e-04]),
 array([-1.21161061e+00,  3.38533189e-04]),
 array([-1.11468176e+00, -2.03119913e-04]),
 array([-1.02550722e+00,  1.21871948e-04]),
 array([-9.43466646e-01, -7.31231688e-05]),
 array([-8.67989314e-01,  4.38739013e-05]),
 array([-7.98550169e-01, -2.63243408e-05]),
 array([-7.34666155e-01,  1.57946045e-05]),
 array([-6.75892863e-01, -9.47676268e-06]),
 array([-6.21821434e-01,  5.68605761e-06]),
 array([-

Q2

In [46]:
def df_w(W):
    dw1 = 0.2 * W[0]
    dw2 = 4 * W[1]
    dW = np.array([dw1, dw2])
    return dW

def sgd_momentum(W, dW, lr, V, beta):
    V = beta * V + (1 - beta) * dW
    W = W - lr * V
    return W, V

def train_p1(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    results = [W]
    for epoch in range(epochs):
        dW = df_w(W)
        W, V = optimizer(W, dW, lr, V, beta=0.5)
        results.append(W)
    return results

train_p1(sgd_momentum, lr=0.6, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.7,  0.4]),
 array([-4.268,  1.12 ]),
 array([-3.79592,  0.136  ]),
 array([-3.3321248, -0.5192   ]),
 array([-2.90029971, -0.22376   ]),
 array([-2.51036919,  0.192472  ]),
 array([-2.16478177,  0.1696216 ]),
 array([-1.86210116, -0.04534952]),
 array([-1.59903478, -0.09841566]),
 array([-1.37155951, -0.00684994]),
 array([-1.1755283 ,  0.04715285]),
 array([-1.006981  ,  0.01757082]),
 array([-0.86228849, -0.01830518]),
 array([-0.73820492, -0.01427696]),
 array([-0.63187084,  0.0048695 ]),
 array([-0.54079155,  0.00859933]),
 array([-4.62804416e-01,  1.45050014e-04]),
 array([-0.39604258, -0.00425615]),
 array([-0.33889911, -0.00134937]),
 array([-0.28999343,  0.00172326]),
 array([-0.24814098,  0.00119166]),
 array([-0.2123263 , -0.00050413]),
 array([-0.18167938, -0.00074707]),
 array([-1.55455157e-01,  2.79448010e-05]),
 array([-0.13301574,  0.00038192]),
 array([-1.13815082e-01,  1.00603444e-04]),
 array([-0.09738585, -0.00016078]),
 

Q3

In [47]:
def df_w(W):
    dw1 = 0.2 * W[0]
    dw2 = 4 * W[1]
    dW = np.array([dw1, dw2])
    return dW

def RMSProp(W, dW, lr, S, gamma):
    epsilon = 1e-6
    S = gamma * S + (1 - gamma) * dW**2
    W = W - lr * dW / (np.sqrt(S) + epsilon)
    return W, S

def train_p1(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    for epoch in range(epochs):
        dW = df_w(W)
        W, S = optimizer(W, dW, lr, S, gamma=0.9)
        results.append(W)
    return results

train_p1(RMSProp, lr=0.3, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.0513197 , -1.05131708]),
 array([-3.43519553, -0.59152376]),
 array([-2.95893489, -0.3294397 ]),
 array([-2.56546089, -0.17756504]),
 array([-2.22920358, -0.09163272]),
 array([-1.93626564, -0.04494508]),
 array([-1.67817504, -0.02081429]),
 array([-1.44934809, -0.00903562]),
 array([-1.24588029, -0.00364592]),
 array([-1.06490135, -0.00135352]),
 array([-9.04200650e-01, -4.56447225e-04]),
 array([-7.61994932e-01, -1.37563947e-04]),
 array([-6.36776983e-01, -3.62604278e-05]),
 array([-5.27213771e-01, -8.11346375e-06]),
 array([-4.32077091e-01, -1.47475425e-06]),
 array([-3.50197152e-01, -2.02787524e-07]),
 array([-2.80433359e-01, -1.84235524e-08]),
 array([-2.21658617e-01, -7.67771777e-10]),
 array([-1.72754375e-01,  7.80432778e-12]),
 array([-1.32614084e-01, -5.05777072e-13]),
 array([-1.00152823e-01,  6.19098174e-14]),
 array([-7.43209130e-02, -1.13368674e-14]),
 array([-5.41193712e-02,  2.80153177e-15]),
 array([-3.86152607e-02, -8.81296

Q4

In [52]:
def df_w(W):
    dw1 = 2 * W[0]
    dw2 = 2 * W[1]
    dW = np.array([dw1, dw2])
    return dW

def Adam(W, dW, lr, V, S, beta1, beta2, t):
    epsilon = 1e-6
    V = beta1 * V + (1 - beta1) * dW
    S = beta2 * S + (1 - beta2) * (dW**2)
    V_corrected = V / (1 - beta1**t)
    S_corrected = S / (1 - beta2**t)
    W = W - (lr / (np.sqrt(S_corrected) + epsilon)) * V_corrected
    return W, V, S

def train_p1(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    for t in range(1, epochs + 1):
        dW = df_w(W)
        W, V, S = optimizer(W, dW, lr, V, S, beta1=0.9, beta2=0.999, t=t)
        results.append(W)
    return results

train_p1(Adam, lr=0.2, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.80000002, -1.80000005]),
 array([-4.60025442, -1.60082456]),
 array([-4.40094793, -1.4031727 ]),
 array([-4.2022769 , -1.20787833]),
 array([-4.0044494 , -1.01592758]),
 array([-3.80768526, -0.82847323]),
 array([-3.61221601, -0.64684178]),
 array([-3.41828472, -0.47252786]),
 array([-3.22614569, -0.30716958]),
 array([-3.03606402, -0.1524988 ]),
 array([-2.84831497, -0.01026352]),
 array([-2.66318316,  0.11787525]),
 array([-2.48096154,  0.23046135]),
 array([-2.30195015,  0.32635844]),
 array([-2.12645461,  0.4048417 ]),
 array([-1.95478434,  0.46564939]),
 array([-1.78725056,  0.50898781]),
 array([-1.62416397,  0.53549427]),
 array([-1.46583223,  0.54617132]),
 array([-1.31255712,  0.54230805]),
 array([-1.1646316 ,  0.52540203]),
 array([-1.0223366 ,  0.49709062]),
 array([-0.88593779,  0.45909517]),
 array([-0.75568226,  0.41317791]),
 array([-0.63179524,  0.36110905]),
 array([-0.51447691,  0.30464066]),
 array([-0.40389948,  0.24548